virhi_admin_admin:
    path:     /demo
    defaults: { _controller: VirhiAdminBundle:Demo:index }

virhi_admin_admin_sidebar:
    path:     /demo/sidebar
    defaults: { _controller: VirhiAdminBundle:Demo:sidebar }
